version: '3'

services:
  cardano-node:
    image: cardanocommunity/cardano-node:latest
    init: true
    hostname: cardano-node
    environment:
      NETWORK: ${NETWORK}
      SOCKET: "${CNODE_HOME}/sockets/node.socket" 
      UPDATE_CHECK: "N"
    volumes:
      - node-db:/opt/cardano/cnode/db
      - node-ipc:/opt/cardano/cnode/sockets
      - node-cfg:/opt/cardano/cnode/priv/files
      - ./scripts/:/scripts/
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "netstat -ntlp | grep 12798"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: ghcr.io/intersectmbo/cardano-db-sync:sancho-3-0-0
    hostname: cardano-db-sync
    environment:
      DISABLE_LEDGER: ${DISABLE_LEDGER}
      NETWORK: ${NETWORK:-mainnet}
      POSTGRES_HOST: postgress
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RESTORE_SNAPSHOT: ${RESTORE_SNAPSHOT:-}
      RESTORE_RECREATE_DB: N
      EXTRA_DB_SYNC_ARGS: ${EXTRA_DB_SYNC_ARGS:-}
    healthcheck:
      test: ["CMD-SHELL", "/scripts/lib/dbsync_healthcheck.sh"]
      interval: 60s
      timeout: 10s
    depends_on:
      # Depend on both services to be healthy before starting.
      #cardano-node:
      #  condition: service_healthy
      #postgress:
      #  condition: service_healthy
      - postgress
      - cardano-node
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
      - ./scripts/:/scripts/
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgress:
    image: postgres:16-bullseye
    hostname: postgress
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./scripts/:/scripts/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:  ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      timeout: 5s
      # retries: 5
    command: postgres
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Develpoment and Testing
  # swagger:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"
  #   environment:
  #     API_URL: http://127.0.0.1:8050/

  postgrest:
    image: postgrest/postgrest:v12.0.1
    hostname: postgrest
    depends_on:
      - postgress
    ports:
      - 8050:8050
      #- 3000:3000
    volumes:
      - ./scripts/:/scripts/
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgress:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${RPC_SCHEMA}
      PGRST_SERVER_PORT: 8050
      PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:8050
      PGRST_DB_MAX_ROWS: 1000
    # healthcheck:
    #   test: ["CMD-SHELL", "/bin/curl -f http://localhost:8050/ || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  haproxy:
    image: haproxy:2.9.0-bookworm
    hostname: haproxy
    depends_on:
      - cardano-node
      - cardano-db-sync
      - postgress
      - postgrest
    volumes:
      - ./configs/haproxy/:/usr/local/etc/haproxy/
      - ./scripts/:/scripts/
    ports:
      - 8053:8053
    healthcheck:
      test: ["CMD-SHELL", "haproxy -c -- /usr/local/etc/haproxy/haproxy.cfg"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
  node-cfg:
  db-sync-data:
  postgresdb: